NAVI:
  NUM_STEPS: 1000
  GT_OCC_MAP_TYPE: 'NAV_MESH'
  NUM_STEPS_EXPLORE: 1
  THRESH_REACH: 0.8
  HFOV: 360
  PERCEPTION: 'None' # possible choices 'Anticipation', 'Potential', 'UNet_Potential'
  STRATEGY: 'FME'
  FLAG_VISUALIZE_MIDDLE_TRAJ: False
  D_type: 'None'
  FLAG_VISUALIZE_FRONTIER_POTENTIAL: False

SEM_MAP:
  FLAG_VISUALIZE_EGO_OBS: False

SAVE:
  TESTING_RESULTS_FOLDER: 'output/TESTING_RESULTS_360degree_FME_NAVMESH_MAP_1STEP_1000STEPS'
  LARGE_TESTING_RESULTS_FOLDER: 'output/LARGE_TESTING_RESULTS_360degree_FME_NAVMESH_MAP_1STEP_500STEPS'

MP:
  PROC_PER_GPU: 1
