MAIN:
  SPLIT: 'train'

NAVI:
  NUM_STEPS: 500
  GT_OCC_MAP_TYPE: 'NAV_MESH'
  HFOV: 360
  PERCEPTION: Potential
  STRATEGY: FME
  D_type: 'Skeleton'
  FLAG_VISUALIZE_MIDDLE_TRAJ: True
  NUM_STEPS_EXPLORE: 1

PRED:
  TYPE: 'VIEW'
  VIEW:
    BATCH_SIZE: 3
    CHECKNAME: resnet
    DEVICE: cuda
    DIVIDE_AREA: 100
    EPOCHS: 6
    EVAL_INTERVAL: 1
    FLAG_VISUALIZE_PRED_LABELS: False
    INPUT: depth_and_sem
    INPUT_CHANNEL: 43 # 42 + 1
    OUTPUT_CHANNEL: 4
    INPUT_WH: (256, 256)
    LOSS_TYPE: L1
    NUM_GENERATED_SAMPLES_PER_SCENE: 1000
    NUM_WORKERS: 2
    RESUME: ''
    SAVED_FOLDER: 'output/model_weights_RESNET_input_view'
    STEP_GAP: 5
    LR: 1e-3
    NUM_PROCESS: 8
    multiprocessing: 'mp'
    GEN_SAMPLES_SAVED_FOLDER: 'output/training_data_input_view_1000samples'


SAVE:
  TESTING_RESULTS_FOLDER: ''

SEM_MAP:
  CELL_SIZE: 0.05
  GRID_CLASS_SIZE: 42
  FLAG_VISUALIZE_EGO_OBS: False