NAVI:
  NUM_STEPS: 1000
  GT_OCC_MAP_TYPE: 'NAV_MESH'
  NUM_STEPS_EXPLORE: 1
  THRESH_REACH: 0.8
  HFOV: 90
  PERCEPTION: 'UNet_Potential' # possible choices 'Anticipation', 'Potential', 'UNet_Potential'
  STRATEGY: 'Greedy'
  FLAG_VISUALIZE_MIDDLE_TRAJ: False
  D_type: 'Sqrt_R'
  FLAG_VISUALIZE_FRONTIER_POTENTIAL: False

SEM_MAP:
  FLAG_VISUALIZE_EGO_OBS: False

SAVE:
  TESTING_RESULTS_FOLDER: 'output/TESTING_RESULTS_90degree_Greedy_NAVMESH_MAP_UNet_OCCandSEM_Potential_1STEP_1000STEPS'
  LARGE_TESTING_RESULTS_FOLDER: 'output/LARGE_TESTING_RESULTS_90degree_Greedy_NAVMESH_MAP_UNet_OCCandSEM_Potential_1STEP_1000STEPS'

MP:
  PROC_PER_GPU: 4

PRED:
  PARTIAL_MAP:
    BATCH_SIZE: 24
    CHECKNAME: unet
    DEVICE: cuda
    DIVIDE_AREA: 100
    EPOCHS: 30
    EVAL_INTERVAL: 2
    FLAG_VISUALIZE_PRED_LABELS: false
    INPUT: occ_and_sem
    INPUT_CHANNEL: 45 # 42 + 3
    OUTPUT_CHANNEL: 4
    INPUT_WH: (256, 256)
    LOSS_TYPE: L1
    NEIGHBOR_SIZE: 20
    NUM_GENERATED_SAMPLES_PER_SCENE: 1000
    NUM_WORKERS: 16
    RESUME: ''
    SAVED_FOLDER: 'output/model_weights_UNet_input_partial_map'
    STEP_GAP: 5
    LR: 1e-3
    NUM_PROCESS: 24
    multiprocessing: 'mp'
    GEN_SAMPLES_SAVED_FOLDER: 'output/training_data_input_partial_map_1000samples'
