NAVI:
  NUM_STEPS: 2000
  GT_OCC_MAP_TYPE: 'NAV_MESH'
  NUM_STEPS_EXPLORE: 1
  THRESH_REACH: 0.8
  HFOV: 360
  PERCEPTION: 'Potential' # possible choices 'Anticipation', 'Potential', 'UNet_Potential'
  STRATEGY: 'Greedy'
  FLAG_VISUALIZE_MIDDLE_TRAJ: False
  D_type: 'Sqrt_R'
  FLAG_VISUALIZE_FRONTIER_POTENTIAL: False

SEM_MAP:
  FLAG_VISUALIZE_EGO_OBS: False

SAVE:
  TESTING_RESULTS_FOLDER: 'output/TESTING_RESULTS_360degree_Greedy_NAVMESH_MAP_GT_Potential_1STEP_2000STEPS'
  LARGE_TESTING_RESULTS_FOLDER: 'output/LARGE_TESTING_RESULTS_360degree_Greedy_NAVMESH_MAP_GT_Potential_1STEP_2000STEPS'

EVAL:
  SIZE: 'large'
  USE_ALL_START_POINTS: True

MP:
  PROC_PER_GPU: 3
